# Generated by Django 6.0.2 on 2026-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('payment_submitted', 'Payment Submitted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
