# Generated by Django 6.0.2 on 2026-03-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transportregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportregistration',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=8),
        ),
        migrations.AddField(
            model_name='transportregistration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
