# Generated by Django 6.0.2 on 2026-04-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routechangerequest',
            name='requested_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_routes', to='transport.route'),
        ),
    ]
