# Generated by Django 6.0.2 on 2026-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_routechangerequest_requested_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='tracker_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
